export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import SessionProvider from "@/components/Providers/SessionProvider";
import "./globals.css";
import ToastBox from "@/components/Common/Toast/ToastBox";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SessionProvider session={session}>
          <main>{children}</main>
        </SessionProvider>
        <ToastBox />
      </body>
    </html>
  );
}
